/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.buttons.formas;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;

/**
 *
 * @author pedro
 */
public class FrmRB extends javax.swing.JFrame {

    /**
     * Creates new form FrmRB
     */
    public FrmRB() {
        initComponents();
        //todas las cosas se deben poner después de esta instrucción
        asignarRadioButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgroupEstadoCivil = new javax.swing.ButtonGroup();
        lblTítulo = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblNacionalidad = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        rbCasado = new javax.swing.JRadioButton();
        rbSoltero = new javax.swing.JRadioButton();
        rbDivorciado = new javax.swing.JRadioButton();
        rbUnionLibre = new javax.swing.JRadioButton();
        rbHombre = new javax.swing.JRadioButton();
        rbMujer = new javax.swing.JRadioButton();
        rbMexicana = new javax.swing.JRadioButton();
        rbExtranjera = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Radio Button");

        lblTítulo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTítulo.setText("Encuesta");

        lblEstadoCivil.setText("Estado Civil");

        lblGenero.setText("Género");

        lblNacionalidad.setText("Nacionalidad");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        rbCasado.setSelected(true);
        rbCasado.setText("Casado");

        rbSoltero.setText("Soltero");

        rbDivorciado.setText("Divorciado");

        rbUnionLibre.setText("Unión Libre");

        rbHombre.setText("Hombre");

        rbMujer.setText("Mujer");

        rbMexicana.setText("Mexicana");

        rbExtranjera.setText("Extranjera");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblNacionalidad)
                        .addComponent(lblEstadoCivil)
                        .addComponent(lblTítulo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbHombre)
                        .addGap(18, 18, 18)
                        .addComponent(rbMujer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGenero)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbCasado)
                                .addGap(18, 18, 18)
                                .addComponent(rbSoltero)
                                .addGap(18, 18, 18)
                                .addComponent(rbDivorciado)
                                .addGap(18, 18, 18)
                                .addComponent(rbUnionLibre))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbMexicana)
                        .addGap(18, 18, 18)
                        .addComponent(rbExtranjera)))
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblTítulo)
                .addGap(51, 51, 51)
                .addComponent(lblEstadoCivil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCasado)
                    .addComponent(rbSoltero)
                    .addComponent(rbDivorciado)
                    .addComponent(rbUnionLibre))
                .addGap(27, 27, 27)
                .addComponent(lblGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbHombre)
                    .addComponent(rbMujer))
                .addGap(14, 14, 14)
                .addComponent(lblNacionalidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMexicana)
                    .addComponent(rbExtranjera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String estadoCivil = seleccionarEstadoCivil();
        System.out.println("Elegiste " + estadoCivil);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    public String seleccionarEstadoCivil(){
        
        Enumeration <AbstractButton> btnGrp = //regresa una enumeración 
                bgroupEstadoCivil.getElements();//recupera todos los elementos del grupo
        
        String resultado = "";
        
        while(btnGrp.hasMoreElements()){
            JRadioButton btnAux = (JRadioButton)btnGrp.nextElement();
            //saca cada botón con sus propieades y lo convierte en uno de esos
            if(btnAux.isSelected()){
                resultado  = btnAux.getText();
                break;
            }
        }
        
        return resultado;
    }
    
    
    public void asignarRadioButtons(){
        /*esto sirve para que los botones no se seleccionen todos de manera
        simultánea. Presionamos selected en el diseño de alguno, para que
        se quede activo y no haya problema de que se queden vacíos*/
        bgroupEstadoCivil.add(rbCasado);
        bgroupEstadoCivil.add(rbSoltero);
        bgroupEstadoCivil.add(rbDivorciado);
        bgroupEstadoCivil.add(rbUnionLibre);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgroupEstadoCivil;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNacionalidad;
    private javax.swing.JLabel lblTítulo;
    private javax.swing.JRadioButton rbCasado;
    private javax.swing.JRadioButton rbDivorciado;
    private javax.swing.JRadioButton rbExtranjera;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMexicana;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JRadioButton rbSoltero;
    private javax.swing.JRadioButton rbUnionLibre;
    // End of variables declaration//GEN-END:variables
}
